[package]
name = "mk"
version = "0.1.3"
authors = ["Edward Fitz Abucay <gh:@ffimnsr>"]
edition = "2021"
readme = "README.md"
description = "Yet another simple task runner 🦀"
categories = ["command-line-utilities", "development-tools"]
homepage = "https://github.com/ffimnsr/mk-rs"
repository = "https://github.com/ffimnsr/mk-rs"
license = "MIT OR Apache-2.0"
keywords = ["command-line", "task-runner", "cli", "runner", "utility"]
exclude = [".gitignore"]

[lib]
name = "mk_lib"
path = "src/lib.rs"

[[bin]]
name = "mk"
path = "src/cli/bin/main.rs"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
console = "0.15.10"
env_logger = "0.11.6"
indicatif = "0.17.9"
log = "0.4.22"
prettytable-rs = "0.10.0"
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.9"
which = "7.0.1"

[dev-dependencies]
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
snapbox = "0.6.21"
tempfile = "3.14.0"
trycmd = "0.15.8"
